In [ ]:
text="""We can notice the occurrence of graphs everywhere.
When faced with decision making one of the first approaches that are thaught to children are decision trees.
Later on, we are prompted to draw mind maps. With a little bit of observation, we can see that social circles are also graphs.
Roads and cities can be graphs, molecules can be graphs and even citing papers in this article can form a graph.
So what is a graph exactly?
We can imagine it as a set of nodes that are connected with edges.
Both of these can carry information, for example, gas consumption or time needed to travel from one city to another.
Networks can have many different qualities, they can be directed or undirected, connected or unconnected, bipartite, etc.
Graph traits can be represented by node, edge, and graph features.
Graph theory started developing way before we ever knew about computers or let alone cryptocurrency.
While there are still many unanswered theoretical questions in this field alone, scientists then started using computers to solve certain graph problems such as searching for the shortest path or perhaps the lowest cost between two nodes.
What comes next? In the modern day and age, we became baffled by the results artificial intelligence can bring.
Art crafted at the hands of a computer, whole conversations with our refrigerators, face recognition to unlock our phones and so much more! Image recognition uses matrices as input and speech recognition manipulates sequences.
Experts in this field of research asked a wonderful question — what would happen if we trained our models on graphs? While it did take some adjusting and changes, we now have many different ML models for such tasks and we used one of them to show just how useful they can be.
A Bitcoin transaction is the transfer of value from one Bitcoin address to another.
While understanding the mechanisms in detail is not crucial, it does explain why tackle this problem in the first place.
First, the transaction is initiated when the sender creates a new transaction of funds.
This includes specifying the recipient, the amount of money sent, and other information.
It generates a unique private key that is later used for verification.
The transaction is then broadcasted to the Bitcoin network and this is where graphs come into the equation.
Verification by miners on the network who solve complex mathematical problems is required for the funds to go through.
Now the transaction is finally added to the blockchain and it is considered confirmed.
When a transaction is broadcasted, it is picked up and forwarded by multiple nodes.
A few years back an interesting article was published by Mark Weber called Experimenting with Graph Convolutional Networks for Financial Forensics.
It provides an Eliptic Data Set of Bitcoin Transaction Graph. The nodes represent transactions and edges the flow of Bitcoins between them.
This graph is not connected but can be viewed as a set of connected directed graphs each in a different timeframe.
Each step captures 3 hours of continuous network traffic. The steps are evenly spaced with 2 weeks between graphs.
Altogether there are 49 timeframes, 203,769 nodes, and 234,355 edges.
There are 3 different labels for the nodes.
The transaction can be labeled as licit, illicit, or unknown.
Each node also has 166 features. Let’s choose one transaction and look at its features.
The first 94 are local information that is obtained at the initialization.
For every graph, each node has its own neighborhood of nodes that are one hop away.
The quantity of these nodes is described as a node degree.
If we want to represent the graph even better it is good to learn the neighborhood properties as well, so the remaining features are aggregated features of these neighbors.
An example of aggregation would be the maximum, minimum, standard deviation, and correlation coef
ficients of neighboring local information.
Do all neighbors hold the same weight?
Are illicit nodes perhaps more important than licit ones? We ended up with 2 different strategies.
First, we will treat all the neighboring nodes as equal using a Graph Convolutional Network model, or GCN for short.
We decided to compare the result with the one of a Graph Attention Network (GAT) model and see which one performs better.
This last one presumes not all nodes are of the same importance by giving them different weights.
But how should we measure our classification performance?
There are many measures and we opted for the F1 score.
Considering our particular situation the worst possible prediction is a false negative one.
Predicting a node to be licit and it is actually illicit is way worse than the other way around, so this score works best in this scenario.
Each node of the graph is represented as a feature vector.
Every single one of these is then updated by aggregating information from its neighboring nodes.
The process is named graph convolution and is largely based on the convolution in traditional convolutional neural networks (CNNs).
This model is just one of many in the graph neural network (GNN) family.
They all generate embeddings that are later used for downstream tasks.
If two embeddings are close in their embedding space the nodes in the observed graph are similar.
The reason why we need these and not just use classic CNNs is that graphs in reality have no order.
The structure of a graph is permutable and the output of the model cannot depend on its physical structure.
Now to overcome this problem let’s look at the basic GNN structure. Each node gets its own computational graph.
We calculate the embeddings in 3 crucial steps. First, each neighboring node sends a message.
The messages are then aggregated and finally, the embedding of our node is updated.
The only difference when using GAT is that we do not take the average but instead we add attention weights to each message.
These are also learned.
This way we can put more attention to the important bits of the data we used for training.
In the picture above we can see that K layers are used, K being the last one.
This means we acquire data from K-hops away and only the nodes whose paths are of this length or less can influence our final embedding.
The segments of code that are being shown here are only the important parts that we thought could use some explaining.
The whole program is available on GitHub. It is based on the PyTorch Geometric module that is built on top of PyTorch.
It provides a set of tools for deep learning on graphs.
Firstly, let’s view how to interpret the data.
It comes in 3 files: one documents the 3 possible classes, the second has all of the features and the last one gives us an edge index.
We then used NetworkX implementation for our graphs.
Index 0 represents the illicit label, 1 is the licit label and 2 is for all of the unlabeled nodes.
There are some interesting statistics to be seen in our Colab, so we recommend you check it out!
We used 39 of the graphs for the training set on which we trained the model and the other 10 for the testing set
Then we implemented our models.
We use PyTorch Geometric’s implementation for the convolution layers.
This works for both GCN and GAT because we have a separate configuration part where we define the parameters and decide which convolution model to use.
We optimized the training by doing repeated k-fold cross-validation.
Instead of just having trained the model and validating the model once, we split out the training set into k equally sized parts.
Then the model is trained on the k-1 parts and later on validated on the remaining 1.
This process is repeated k times, with each part or so-called fold used once as the validation set.
This approach helps to reduce the impact of the randomness in the train-validation split on the performance and makes the model more reliable.
This is the algorithm.
"""

In [ ]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer


In [ ]:
tokenizer=Tokenizer()
tokenizer.fit_on_texts([text])

In [ ]:
tokenizer.word_index

{'the': 1,
 'of': 2,
 'is': 3,
 'we': 4,
 'and': 5,
 'are': 6,
 'a': 7,
 'to': 8,
 'this': 9,
 'graph': 10,
 'for': 11,
 'in': 12,
 'can': 13,
 'one': 14,
 'nodes': 15,
 'on': 16,
 'that': 17,
 'it': 18,
 'graphs': 19,
 'be': 20,
 'as': 21,
 'our': 22,
 'model': 23,
 'with': 24,
 'or': 25,
 'node': 26,
 'transaction': 27,
 'each': 28,
 'set': 29,
 'by': 30,
 'used': 31,
 'then': 32,
 'k': 33,
 'first': 34,
 'so': 35,
 'these': 36,
 'different': 37,
 'features': 38,
 'network': 39,
 'all': 40,
 'information': 41,
 'many': 42,
 'there': 43,
 'not': 44,
 '3': 45,
 'its': 46,
 'when': 47,
 'later': 48,
 'connected': 49,
 'from': 50,
 'have': 51,
 'way': 52,
 'at': 53,
 'more': 54,
 'trained': 55,
 'just': 56,
 'bitcoin': 57,
 'an': 58,
 'data': 59,
 'licit': 60,
 'illicit': 61,
 'neighboring': 62,
 'convolution': 63,
 'use': 64,
 'training': 65,
 'see': 66,
 'also': 67,
 'what': 68,
 'edges': 69,
 'networks': 70,
 'they': 71,
 'while': 72,
 'using': 73,
 'between': 74,
 'recognition': 75,


In [ ]:
input_seq=[]
for sentence in text.split('\n'):
  tokenized_sentence=tokenizer.texts_to_sequences([sentence])[0]

  for i in range(1,len(tokenized_sentence)):
    input_seq.append(tokenized_sentence[:i+1])

In [ ]:
input_seq

[[4, 13],
 [4, 13, 177],
 [4, 13, 177, 1],
 [4, 13, 177, 1, 178],
 [4, 13, 177, 1, 178, 2],
 [4, 13, 177, 1, 178, 2, 19],
 [4, 13, 177, 1, 178, 2, 19, 179],
 [47, 180],
 [47, 180, 24],
 [47, 180, 24, 101],
 [47, 180, 24, 101, 181],
 [47, 180, 24, 101, 181, 14],
 [47, 180, 24, 101, 181, 14, 2],
 [47, 180, 24, 101, 181, 14, 2, 1],
 [47, 180, 24, 101, 181, 14, 2, 1, 34],
 [47, 180, 24, 101, 181, 14, 2, 1, 34, 182],
 [47, 180, 24, 101, 181, 14, 2, 1, 34, 182, 17],
 [47, 180, 24, 101, 181, 14, 2, 1, 34, 182, 17, 6],
 [47, 180, 24, 101, 181, 14, 2, 1, 34, 182, 17, 6, 183],
 [47, 180, 24, 101, 181, 14, 2, 1, 34, 182, 17, 6, 183, 8],
 [47, 180, 24, 101, 181, 14, 2, 1, 34, 182, 17, 6, 183, 8, 184],
 [47, 180, 24, 101, 181, 14, 2, 1, 34, 182, 17, 6, 183, 8, 184, 6],
 [47, 180, 24, 101, 181, 14, 2, 1, 34, 182, 17, 6, 183, 8, 184, 6, 101],
 [47, 180, 24, 101, 181, 14, 2, 1, 34, 182, 17, 6, 183, 8, 184, 6, 101, 185],
 [48, 16],
 [48, 16, 4],
 [48, 16, 4, 6],
 [48, 16, 4, 6, 186],
 [48, 16, 4, 6, 18

In [ ]:
max_len=max(len(x) for x in input_seq)
print(max_len)

53


In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_input_seq=pad_sequences(input_seq,maxlen=max_len,padding='pre')

In [ ]:
print(padded_input_seq)

[[  0   0   0 ...   0   4  13]
 [  0   0   0 ...   4  13 177]
 [  0   0   0 ...  13 177   1]
 ...
 [  0   0   0 ...   0   9   3]
 [  0   0   0 ...   9   3   1]
 [  0   0   0 ...   3   1 520]]


In [ ]:
X=padded_input_seq[:,:-1]
print(X)

[[  0   0   0 ...   0   0   4]
 [  0   0   0 ...   0   4  13]
 [  0   0   0 ...   4  13 177]
 ...
 [  0   0   0 ...   0   0   9]
 [  0   0   0 ...   0   9   3]
 [  0   0   0 ...   9   3   1]]


In [ ]:
y=padded_input_seq[:,-1]
print(y)

[ 13 177   1 ...   3   1 520]


In [ ]:
X.shape

(1271, 52)

In [ ]:
y.shape

(1271,)

In [ ]:
from tensorflow.keras.utils import to_categorical
y=to_categorical(y,num_classes=len(tokenizer.word_index)+1)

In [ ]:
y.shape

(1271, 521)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense

In [ ]:
model = Sequential()
model.add(Embedding(521, 100, input_length=max_len - 1))  # Specify input_length
model.add(LSTM(213))
model.add(Dense(521, activation='softmax'))

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.summary()

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm (LSTM)                          │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.fit(X,y,epochs=100)

Epoch 1/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 6s 14ms/step - accuracy: 0.0603 - loss: 6.1005
Epoch 2/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - accuracy: 0.0642 - loss: 5.5992
Epoch 3/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.0590 - loss: 5.5616
Epoch 4/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.0595 - loss: 5.4973
Epoch 5/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.0593 - loss: 5.4743
Epoch 6/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.0733 - loss: 5.2476
Epoch 7/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.0813 - loss: 5.1395
Epoch 8/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.0966 - loss: 4.9571
Epoch 9/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.1235 - loss: 4.7817
Epoch 10/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.1570 - loss: 4.5606
Epoch 11/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.1724 - loss: 4.3269
Epoch 12/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accur

In [ ]:
import numpy as np


In [ ]:
pred_text="The messages"

for i in range(10):
#tokenize
  token_text=tokenizer.texts_to_sequences([pred_text])[0]
  #pad
  padded_token_text=pad_sequences([token_text],maxlen=max_len,padding='pre')
  #print(padded_token_text)
  #predict
  pos=np.argmax(model.predict(padded_token_text))
  for word,index in tokenizer.word_index.items():
    if index==pos:
      pred_text=pred_text + " " + word
      print(pred_text)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step
The messages are
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step
The messages are then
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
The messages are then aggregated
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step
The messages are then aggregated and
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
The messages are then aggregated and finally
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step
The messages are then aggregated and finally the
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
The messages are then aggregated and finally the embedding
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step
The messages are then aggregated and finally the embedding of
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
The messages are then aggregated and finally the embedding of our
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
The messages are then aggregated and finally the embedding of our node
